# Generated by Django 3.1.3 on 2020-11-19 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building_name', models.CharField(max_length=200)),
                ('Building_number', models.IntegerField()),
                ('State', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Pin_code', models.IntegerField(default=0)),
                ('Purpose', models.CharField(max_length=200)),
                ('Phase', models.CharField(max_length=200)),
                ('Tarif', models.CharField(max_length=200)),
                ('Reg_Date', models.DateField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Comment', models.TextField(max_length=200)),
                ('status', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Registration_date', models.DateField()),
                ('User_role', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reading_date', models.DateField(default=0)),
                ('Reading', models.IntegerField(default=0)),
                ('r_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybill.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building_name', models.CharField(max_length=200)),
                ('Building_number', models.IntegerField()),
                ('Date_from', models.DateField(default=0)),
                ('Previous_reading', models.IntegerField(default=0)),
                ('Date_to', models.DateField(default=0)),
                ('Current_reading', models.IntegerField(default=0)),
                ('Amount', models.FloatField(default=0)),
                ('Bill_date', models.DateField(default=0)),
                ('r_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybill.buildings')),
            ],
        ),
        migrations.AddField(
            model_name='buildings',
            name='buil_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybill.registration'),
        ),
    ]
