# Generated by Django 3.1.3 on 2020-12-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='Difference',
            field=models.FloatField(default=0),
        ),
    ]
